version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION: mysql
          - DB_DATABASE: laravel
          - DB_USERNAME: root

      - image: circleci/mysql:8.0-ram
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: laravel

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install pdo_mysql

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "backend/composer.json" }}
            - v1-dependencies-

      - run:
          working_directory: backend
          command: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "backend/composer.json" }}
          paths:
            - .backend/vendor

      - run: echo "APP_KEY=" > .env
      - run: php artisan key:generate
      - run: php artisan migrate

      - run: .backend/vendor/bin/phpunit

  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - add_ssh_keys:
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/app/backend && git pull origin main'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
