version: 2

jobs:
  # build ジョブ: CircleCI 上で Docker コンテナを作成してテストする
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Echo Test
          command: echo "CircleCI Test"
  # deploy ジョブ: EC2 に SSH 接続して、デプロイを実行する
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - add_ssh_keys:
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/app && git pull origin main'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
